"""Prove the ESP32 firmware frames the ground station byte-for-byte.

Compiles ``firmware/airone_cansat/airone_frame.h`` with a tiny C driver, packs
a frame in C, and asserts it is identical to ``protocol.pack_frame`` and that
the Python parser accepts the C-generated bytes with a valid CRC.

Skipped when no C compiler is available.
"""
import os
import shutil
import subprocess
import tempfile

import pytest

from src.telemetry import protocol

_CC = shutil.which("cc") or shutil.which("gcc")
_needs_cc = pytest.mark.skipif(_CC is None, reason="no C compiler available")

_FW_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "firmware",
    "airone_cansat",
)
# The firmware may be distributed as a separate package (it flashes onto the
# CanSat, not the laptop). When the firmware source is not co-located with the
# ground-station software, this cross-artifact parity test skips honestly rather
# than failing.
_needs_firmware = pytest.mark.skipif(
    not os.path.isfile(os.path.join(_FW_DIR, "airone_frame.h")),
    reason="firmware source not co-located (shipped as separate CanSat package)",
)

_C_DRIVER = r"""
#include <stdio.h>
#include "airone_frame.h"
int main(void){
    const char* payload =
        "{\"bmp581_pressure\":{\"value\":98123.4,\"unit\":\"Pa\",\"sensor_id\":\"BMP581\"}}";
    uint8_t out[512];
    size_t n = airone_pack_frame(out, sizeof(out), AIRONE_PT_SENSOR_DATA,
                                 42, 1700000000000000ULL,
                                 (const uint8_t*)payload, strlen(payload));
    for (size_t i=0;i<n;i++) printf("%02x", out[i]);
    return 0;
}
"""

_PAYLOAD = (
    b'{"bmp581_pressure":{"value":98123.4,"unit":"Pa","sensor_id":"BMP581"}}'
)


@_needs_cc
@_needs_firmware
def test_firmware_frame_matches_python_byte_for_byte():
    with tempfile.TemporaryDirectory() as td:
        src = os.path.join(td, "driver.c")
        exe = os.path.join(td, "driver")
        with open(src, "w") as fh:
            fh.write(_C_DRIVER)
        subprocess.run(
            [_CC, "-I", _FW_DIR, "-o", exe, src], check=True, capture_output=True
        )
        c_hex = subprocess.run(
            [exe], check=True, capture_output=True, text=True
        ).stdout.strip()

    py = protocol.pack_frame(
        protocol.PacketType.SENSOR_DATA, 42, 1700000000000000, _PAYLOAD
    )
    assert c_hex == py.hex(), "firmware frame differs from ground-station frame"

    # And the Python parser must accept the C-produced bytes with a valid CRC.
    header, payload = protocol.unpack_frame(bytes.fromhex(c_hex))
    assert header["sequence"] == 42
    assert header["packet_type"] == int(protocol.PacketType.SENSOR_DATA)
    assert payload == _PAYLOAD


# ---------------------------------------------------------------------------
# Authenticated frames (FLAGS 0x08 + truncated HMAC-SHA256 tag)
# ---------------------------------------------------------------------------

_LINK_KEY_HEX = "00112233445566778899aabbccddeeff0123456789abcdef0123456789abcdef"
_LINK_KEY = bytes.fromhex(_LINK_KEY_HEX)

_C_AUTH_DRIVER = r"""
#include <stdio.h>
#include "airone_frame.h"
int main(void){
    const char* payload =
        "{\"bmp581_pressure\":{\"value\":98123.4,\"unit\":\"Pa\",\"sensor_id\":\"BMP581\"}}";
    uint8_t key[64];
    size_t klen = airone_hex_to_key("%s", key, sizeof(key));
    if (klen == 0) { printf("BADKEY"); return 0; }
    uint8_t out[512];
    size_t n = airone_pack_frame_auth(out, sizeof(out), AIRONE_PT_SENSOR_DATA,
                                      42, 1700000000000000ULL,
                                      (const uint8_t*)payload, strlen(payload),
                                      key, klen);
    for (size_t i=0;i<n;i++) printf("%%02x", out[i]);
    printf("\n");
    /* SHA-256 known-answer test ("abc") */
    uint8_t d[32]; airone_sha256((const uint8_t*)"abc", 3, d);
    for (int i=0;i<32;i++) printf("%%02x", d[i]);
    printf("\n");
    /* HMAC-SHA256 RFC 4231 test case 2 */
    uint8_t h[32];
    airone_hmac_sha256((const uint8_t*)"Jefe", 4,
                       (const uint8_t*)"what do ya want for nothing?", 28, h);
    for (int i=0;i<32;i++) printf("%%02x", h[i]);
    printf("\n");
    /* A key shorter than 16 bytes must be refused (returns 0). */
    size_t bad = airone_pack_frame_auth(out, sizeof(out), AIRONE_PT_SENSOR_DATA,
                                        1, 1ULL, (const uint8_t*)payload, strlen(payload),
                                        key, 8);
    printf("%%u\n", (unsigned)bad);
    return 0;
}
""" % _LINK_KEY_HEX


def _run_c(source: str) -> str:
    with tempfile.TemporaryDirectory() as td:
        src = os.path.join(td, "driver.c")
        exe = os.path.join(td, "driver")
        with open(src, "w") as fh:
            fh.write(source)
        subprocess.run(
            [_CC, "-Wall", "-I", _FW_DIR, "-o", exe, src], check=True, capture_output=True
        )
        return subprocess.run([exe], check=True, capture_output=True, text=True).stdout


@_needs_cc
@_needs_firmware
def test_firmware_authenticated_frame_matches_python_and_verifies():
    lines = _run_c(_C_AUTH_DRIVER).strip().splitlines()
    c_hex, sha_abc, hmac_jefe, short_key_result = lines

    # Primitive known-answer tests (FIPS 180-4 / RFC 4231).
    assert sha_abc == (
        "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
    )
    assert hmac_jefe == (
        "5bdcc146bf60754e6a042426089575c75a003f089d2739839dec58b964ec3843"
    )
    assert short_key_result == "0", "firmware must refuse keys shorter than 16 bytes"

    py = protocol.pack_frame(
        protocol.PacketType.SENSOR_DATA, 42, 1700000000000000, _PAYLOAD,
        flags=protocol.FLAG_AUTHENTICATED, link_key=_LINK_KEY,
    )
    assert c_hex == py.hex(), "authenticated firmware frame differs from ground-station frame"

    frame = bytes.fromhex(c_hex)
    header, payload = protocol.unpack_frame(frame, link_key=_LINK_KEY)
    assert header["auth_state"] == "AUTHENTICATED"
    assert header["authenticated_flag"] is True
    assert payload == _PAYLOAD

    # Without the key the ground station can see the flag but not verify it.
    header_nokey, _ = protocol.unpack_frame(frame)
    assert header_nokey["auth_state"] == "UNVERIFIABLE"

    # A different key must reject the frame explicitly.
    with pytest.raises(protocol.AuthTagError):
        protocol.unpack_frame(frame, link_key=bytes(32))

    # Tampering with one payload byte breaks the CRC first (fail fast).
    tampered = bytearray(frame)
    tampered[25] ^= 0x01
    with pytest.raises(protocol.FrameError):
        protocol.unpack_frame(bytes(tampered), link_key=_LINK_KEY)
